samples: "config/samples.tsv"

gene_sets:
  - UROSEVIC_RESPONSE_TO_IMIQUIMOD 
  - KEGG_PROTEASOME

ref:
  # ensembl species name
  species: "homo_sapiens"
  # ensembl release version
  release: "111"
  # genome build
  build: "GRCh38"